FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install
# Install additional packages for hot reload
RUN npm install -g @nestjs/cli

COPY . .

EXPOSE 3000

CMD ["npm", "run", "start:dev"]